name: DNSControl

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gacts/install-dnscontrol@v1
      - name: DNSControl check
        run: dnscontrol check

  check-creds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # provider: [cloudflare, digitalocean]
        provider: [cloudflare]
    steps:
      - uses: actions/checkout@v4
      - uses: gacts/install-dnscontrol@v1
      - name: DNSControl check-creds
        run: dnscontrol check-creds ${{ matrix.provider }}
        env:
          TOKEN_CLOUDFLARE: ${{ secrets.TOKEN_CLOUDFLARE }}
          TOKEN_DIGITALOCEAN: ${{ secrets.TOKEN_DIGITALOCEAN }}

  preview:
    needs: [check, check-creds]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gacts/install-dnscontrol@v1
      - name: DNSControl preview
        run: dnscontrol preview
        env:
          TOKEN_CLOUDFLARE: ${{ secrets.TOKEN_CLOUDFLARE }}
          TOKEN_DIGITALOCEAN: ${{ secrets.TOKEN_DIGITALOCEAN }}

  push:
    if: github.event_name == 'push'
    needs: [preview]
    runs-on: ubuntu-latest
    environment: dns
    concurrency:
      group: dns-push
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: gacts/install-dnscontrol@v1
      - name: DNSControl push
        run: dnscontrol push
        env:
          TOKEN_CLOUDFLARE: ${{ secrets.TOKEN_CLOUDFLARE }}
          TOKEN_DIGITALOCEAN: ${{ secrets.TOKEN_DIGITALOCEAN }}
